pref("extensions.infocard.cardStoreMasterPasswordEncryption", true);
pref("extensions.infocard.cardStoreCurrentProfile", true);
pref("extensions.infocard.cardStoreLocalFilePath", "");
pref("extensions.infocard.cardStoreUrl", "");
pref("extensions.identityselector.disabled", false);
pref("extensions.identityselector.advertise", "advertiseSelectorName");
pref("extensions.identityselector.selector_class", "@openinfocard.org/cardstore-file;1");
pref("privacy.item.infocard", false);
pref("extensions.infocard.log.cardspaceDebug", true);
