pref("extensions.infocard.cardStoreMasterPasswordEncryption", true);
pref("extensions.infocard.cardStoreCurrentProfile", true);
pref("extensions.infocard.cardStoreLocalFilePath", "");
pref("extensions.infocard.cardStoreUrl", "");
pref("extensions.identityselector.disabled", false);
pref("extensions.identityselector.contractid", "@xmldap.org/identityselector;1");
pref("extensions.identityselector.advertise", "advertiseSelectorName");
pref("extensions.identityselector.selector_class", "OpeninfocardSelector");
pref("privacy.item.infocard", false);